routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//https://tutsforweb.com/how-to-set-up-task-scheduling-cron-job-in-laravel/
//https://stackoverflow.com/questions/49921916/notify-users-if-their-account-is-going-to-expire-in-5-days-later-laravel
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// die('ddd');
Route::get('/routes', function () {
    $routesname = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->getName();
      });
    $routesuri = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->uri();
      });
    echo"<pre>";print_r($routesname);
    echo"<pre>";print_r($routesuri);
    die;
});

Auth::routes();

Route::get('admin/login', function () {
    return view('auth.login');
});
Route::get('alert', 'AlertController@index')->name('packageAlert');
Route::get('/', 'HomeController@index')->name('homepage');
Route::get('/hosting', 'HomeController@hosting')->name('hosting');
Route::get('plan/configure/{id}', 'HomeController@planConfigure')->name('plan.configure');
Route::get('/about/us', 'HomeController@about')->name('about');
Route::get('/contact/us', 'HomeController@contactUs')->name('contact.us');
Route::post('/save/contact/us', 'HomeController@saveContactDetail')->name('save.contact.detail');
Route::get('/new', 'HomeController@theme');

Route::get('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofile');
Route::post('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofilepost');
Route::get('/userorder', 'UsersprofileController@userOrder')->name('userOrder');

Route::get('home', 'HomeController@index')->name('home');
Route::get('/cart', 'CartController@index')->name('cart');
Route::post('apply/code', 'CartController@applyCode')->name('apply.code');
Route::get('/add-cart/{id}', 'CartController@addcart')->name('addcart');
Route::get('/cart-delete/{id}', 'CartController@deletecart')->name('deletecart');

Route::group(['middleware' =>'auth'], function () {
    Route::get('/checkout', 'CartController@checkout')->name('checkout');
    Route::get('/payment/{payment_method}', 'CartController@checkoutPost')->name('Payment');
    Route::get('/paypalpaymentcancel', 'CartController@paymentCancel')->name('paymentCancel');
    Route::get('/paymentsuccess', 'CartController@paymentSuccess')->name('paymentSuccess');
    Route::post('/razorpaysuccess', 'CartController@razorpaySuccess')->name('razorpaysuccess');
});

Route::get('/remindertousers', 'HomeController@remindertousers')->name('remindertousers');


// Route::group(['middleware' => 'user_permission'], function () {
//     Route::resource('hostings', 'HostingsController');
// });

Route::group(['middleware' => ['user_permission'],'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'name'=>'admin.'], function() {

        Route::get('hostings/about/to/expire/', 'HostingMonitorController@listHostingsABoutToExpire')->name('about.to.expire');
        Route::get('todays/sale', 'HostingMonitorController@todaysSale')->name('todays.sale');

        Route::get('sale/overview/{id}', 'HostingMonitorController@saleOverview')->name('sale.overview');
        Route::get('hosting/overview/{id}', 'HostingMonitorController@saleOverview')->name('hosting.overview');


        //dashboard
    	Route::get('/', 'HomeController@index')->name('home');

    	//hostings routes
    	Route::resource('hostings', 'HostingsController');


    	//users routes
    	Route::resource('users', 'UsersController');
        Route::get('user/roles', 'UsersController@UserRoles')->name('UserRoles');
    	Route::get('adduser/role', 'UsersController@Addrole')->name('addrole');
        Route::post('adduser/role', 'UsersController@Addrole')->name('addrolepost');
        Route::get('edituser/role/{id}', 'UsersController@Editrole')->name('editrole');
        Route::post('edituser/role/{id}', 'UsersController@Editrole')->name('editrolepost');
        Route::DELETE('deleteuser/role/{id}', 'UsersController@destroyUserRole')->name('destroyUserRole');
        Route::get('user/permission', 'UserPermissionsController@index');

        //addon routes
        Route::resource('addons','AddonController');

    	//orders routes
    	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
    	Route::get('/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
    	Route::post('/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');

        
        // routes manager
        Route::resource('routesmanager', 'RoutesmanagerController');
        

        Route::get('slider/list', 'SliderController@index')->name('sliders');
        Route::get('create/slider', 'SliderController@create')->name('slider.create');
        Route::post('save/slider', 'SliderController@store')->name('slider.save');

        Route::any('delete/slider/{id}', 'SliderController@destroy')->name('slider.delete');

        Route::get('edit/slider/{id}', 'SliderController@edit')->name('slider.edit');
        Route::any('update/slider/{id}', 'SliderController@update')->name('slider.update');


        Route::get('feature/list', 'FeatureController@index')->name('features');
        Route::get('create/feature', 'FeatureController@create')->name('feature.create');
        Route::post('save/feature', 'FeatureController@store')->name('feature.save');

        Route::any('delete/feature/{id}', 'FeatureController@destroy')->name('feature.delete');

        Route::get('edit/feature/{id}', 'FeatureController@edit')->name('feature.edit');
        Route::any('update/feature/{id}', 'FeatureController@update')->name('feature.update');

        //offers
        Route::get('offers/list', 'OffersController@index')->name('offers');
        Route::get('create/offers', 'OffersController@create')->name('offers.create');
        Route::post('save/offers', 'OffersController@save')->name('offers.save');

        Route::get('edit/offers/{id}', 'OffersController@edit')->name('offers.edit');
        Route::any('delete/offers/{id}', 'OffersController@destroy')->name('offers.delete');
        Route::any('delete/update/{id}', 'OffersController@update')->name('offers.update');
        Route::post('check/valid/offer/code', 'OffersController@checkValidOfferCode')->name('check.valid.offer.code');

        //contact module
        Route::get('contact/list', 'ContactController@index')->name('contact.list');
        Route::any('delete/contact/{id}', 'ContactController@destroy')->name('contact.delete');

        Route::get('contact/page/detail', 'ContactController@ContactPageDetail')->name('contact.page.detail');
        Route::post('save/contact/page/detail', 'ContactController@saveContactPageDetail')->name('save.contact.page.detail');


    });
});

app/Http/Controllers/Admin/OffersController.php
<?php
namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Offer;
use App\Models\HostingPlan;
use File;
use Response;

use App\Models\Feature;

class OffersController extends Controller
{

    public function __construct(){

        //$this->middleware('auth');
    }

    public function index(Request $request){

        if ($request->ajax()) {

            $data = Offer::latest()->get();

            return DataTables::of($data)->addColumn('action', function($data){

                $edit = route('admin.offers.edit',$data->id);
                $delete = route('admin.offers.delete',$data->id);
                $button = '<a name="edit" id="'.$data->id.'" class="edit btn btn-primary btn-sm" href="'.$edit.'">Edit</a>';
                $button .= '&nbsp;&nbsp;&nbsp;<button type="button" class="delete btn btn-danger btn-sm" onclick="deleteData(this)" data-id="'.$data->id.'" data-url="'.$delete.'">Delete</button>';
                return $button;
            })->rawColumns(['action'])->make(true);
        }

        return view('admin.offers.index');

    }

    public function create(){

        $plans = HostingPlan::all();
        $specific_item = array();
        $restricted_item  = array();
        return view('admin.offers.addoredit',compact('plans','specific_item','restricted_item'));
    }


    public function save(Request $request){

        $validation = (new Offer)->validateOfferDetails($request);

        if($validation->fails()) {
            return back()->withErrors($validation);
        }

        try{
            \DB::beginTransaction();
                (new Offer)->saveOfferDetails($request->except(['_token']));
            \DB::commit();

            return back()->with('success','Offer successfully Created');

        }catch (\Exception $e){

            \DB::rollBack();
            return back()->with('error','Something Wrong');
        }

    }

    public function edit($id=null){

        $plans = HostingPlan::all();
        $route = Offer::find($id);
        $type  = $route->type;
        $specific_item =  json_decode($route->specific_item);
        $restricted_item =json_decode($route->restricted_item);

        return view('admin.offers.addoredit',compact('route','plans','specific_item','restricted_item','type'));
    }

    public function update(Request $request){

        $validation = (new Offer)->validateOfferDetails($request);

        if($validation->fails()) {
            return back()->withErrors($validation);
        }
        try{

            \DB::beginTransaction();
            $response = (new Offer)->checkValidOfferCode($request->except(['_token']));
            if($response == false){
                (new Offer)->saveOfferDetails($request->except(['_token']));
                return back()->with('success','Offer successfully Created');
            }else{
                return back()->with('error','Entered Offer code already Registered');
            }

            \DB::commit();

        }catch (\Exception $e){

            \DB::rollBack();
            return back()->with('error','Something Wrong');
        }
    }



    public function destroy($id=null){

        $response = Offer::find($id);
        if($response->delete()){
            return true;
        }else{
            return false;
        }

    }



    public function checkValidOfferCode(Request $request){

        $ifAny = Offer::where('code',$request['code'])->get();
        if(count($ifAny)>0){
            $msg = "Chosen Offer code is already rgistered.";
            $success = false;
        }else{
            $msg = "Chosen Offer code is available.";
            $success = true;
        }
        return Response::json(array(
            'success' => $success,
            'msg'    => $msg
        ));
    }


}
?>

resources/views/admin/offers/addoredit.blade.php
@extends('admin.layouts.app')
<style type="text/css"> img { display: block; max-width:180px; max-height:180px; width: auto; height: auto; } .error { color: red; } </style>
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">

            <div class="card">
                <div class="card-header card-header-primary">
                  @if(isset($route))
                      <h4 class="card-title ">Update Offer</h4>
                  @else
                      <h4 class="card-title ">Create Offer</h4>
                  @endif
                </div>

                    <div class="card-body">
                        @if(isset($route))
                          {{ Form::model($route, ['route' => ['admin.offers.update', $route->id], 'method' => 'patch','files'=>'true']) }}
                        @else
                            {{ Form::open(['route' => 'admin.offers.save','files'=>'true']) }}
                        @endif

                        <div class="row">
                          <div class=" col-md-12">
                            <label for="name" class="col-form-label">Offer Name</label>
                              {{ Form::text('name',null,['class'=>'form-control','id'=>'name']) }}
                              @if($errors->has('name'))
                                  <div class="error">{{ $errors->first('name') }}</div>
                              @endif
                          </div>
                        </div>

                        <div class="row">
                          <div class=" col-md-12">
                              <label for="description" class="col-form-label">Offer Description</label>
                              {{ Form::textarea('description',null,['class'=>'form-control','id'=>'description','rows'=>'4', 'cols'=>'200']) }}
                              @if($errors->has('description'))
                                  <div class="error">{{ $errors->first('description') }}</div>
                              @endif
                          </div>
                        </div>

                        <div class="row">
                            <div class=" col-md-6">
                                <label for="type" class="col-form-label">Offer Type</label>
                                <select class = "form-control" name="type" id="type" >
                                    <option value="fixed" @if(isset($type) && $type== "fixed") selected @endif >Fixed Type</option>
                                    <option value="percentage" @if(isset($type) && $type== "percentage") selected @endif >Percentage Type</option>
                                </select>

                                @if($errors->has('type'))
                                    <div class="error">{{ $errors->first('type') }}</div>
                                @endif
                            </div>
                            <div class=" col-md-6">
                                <label for="code" class="col-form-label">Offer Code</label>
                                {{ Form::text('code',null,['class'=>'form-control','id'=>'code']) }}
                                <div class="isValidCodeOrNot"  id="isValidCodeOrNot"></div>
                                @if($errors->has('code'))
                                    <div class="error">{{ $errors->first('code') }}</div>
                                @endif
                            </div>
                        </div>

                        <div class="row">
                            <div class=" col-md-6">
                                <label for="start_date" class="col-form-label">Offer Start Date</label>
                                {{ Form::date('start_date',null,['class'=>'form-control','id'=>'start_date']) }}
                                {{ Form::hidden('id',null) }}
                                @if($errors->has('start_date'))
                                    <div class="error">{{ $errors->first('start_date') }}</div>
                                @endif
                            </div>
                            <div class=" col-md-6">
                                <label for="expiry_date" class="col-form-label">Offer Expiry Date</label>
                                {{ Form::date('expiry_date',null,['class'=>'form-control','id'=>'expiry_date	']) }}
                                @if($errors->has('expiry_date'))
                                    <div class="error">{{ $errors->first('expiry_date') }}</div>
                                @endif
                            </div>
                        </div>

                        <div class="row">
                            <div class=" col-md-6">
                                <label for="min_package_amount" class="col-form-label">Minimum Package Amount ( ₹ )</label>
                                {{ Form::text('min_package_amount',null,['class'=>'form-control','id'=>'min_package_amount']) }}
                                @if($errors->has('min_package_amount'))
                                    <div class="error">{{ $errors->first('min_package_amount') }}</div>
                                @endif
                            </div>
                            <div class=" col-md-6">
                                <label for="max_discount" class="col-form-label Discountlabel">Offer Maximum Discount ( % )</label>
                                {{ Form::text('max_discount',null,['class'=>'form-control','id'=>'max_discount']) }}
                                @if($errors->has('max_discount'))
                                    <div class="error">{{ $errors->first('max_discount') }}</div>
                                @endif
                            </div>
                        </div>

                        <div class="row">
                            <div class=" col-md-6">
                                <label for="specific_item" class="col-form-label">Specific Item</label>
                                <select class="specific_item form-control" name="specific_item[]" id="specific_item" multiple="true">
                                    @if(!empty($plans) && isset($plans) )
                                        @foreach($plans as $plan)
                                            <option value="{{$plan->id}}"
                                                    @if(!empty($specific_item)) @if(in_array($plan->id,$specific_item)) selected @endif @endif
                                            >{{$plan->title}}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if($errors->has('specific_item	'))
                                    <div class="error">{{ $errors->first('specific_item') }}</div>
                                @endif
                            </div>

                            <div class=" col-md-6">
                                <label for="restricted_item" class="col-form-label">Restricted Item</label>
                                <select class="restricted_item form-control" name="restricted_item[]" id="restricted_item" multiple="true">
                                    @if(!empty($plans) && isset($plans) )
                                        @foreach($plans as $plan)
                                            <option value="{{$plan->id}}"
                                                    @if(!empty($restricted_item)) @if(in_array($plan->id,$restricted_item)) selected @endif @endif
                                            >{{$plan->title}}</option>
                                        @endforeach
                                    @endif
                                </select>
                                @if($errors->has('restricted_item'))
                                    <div class="error">{{ $errors->first('restricted_item') }}</div>
                                @endif
                            </div>
                        </div>


                        <div class="row">
                          <div class="form-group col-md-6">
                             {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
                          </div>
                        </div>
                    </form>

              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
@endsection




@push('scripts')


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

    <script>

        $('#max_discount').keypress (function( e ) {
            if(!/[0-9]/.test(String.fromCharCode(e.which))){
                return false;
            }
        });

        $('#max_discount').keyup(function(){
			var selected = $('#type').val();
			if(selected!='fixed' && $(this).val() > 100){
				alert("No numbers above 100");
				$(this).val('100');
			}
				
        });

        $(document).ready(function(){
            $(".specific_item").select2({
                placeholder: "Specific Item", //placeholder
                tags: true,
                tokenSeparators: ['/',',',';'," "]
            });
        });

        $(document).ready(function(){
            $(".restricted_item").select2({
                placeholder: " Restricted Item", //placeholder
                tags: true,
                tokenSeparators: ['/',',',';'," "]
            });
        });

        $('#code').keypress (function( e ) {

            if(!/[0-9a-zA-Z-]/.test(String.fromCharCode(e.which)))
                return false;
        });

        $('#code').keyup(function(){
            this.value = this.value.toUpperCase();
            var code = this.value;
            checkForValid(code);
        });

        function checkForValid(code){

            var route ="{{ route('admin.check.valid.offer.code')  }}";

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.post(
                route,
                {code:code},
                function (data) {
                    if(data.success==true){
                        $("#isValidCodeOrNot").empty();
                        $( "#isValidCodeOrNot" ).append( "<strong style='color: green;' > "+ data.msg +" </strong>" );
                        removeMsg();

                    }else{
                        $("#isValidCodeOrNot").empty();
                        $( "#isValidCodeOrNot" ).append( "<strong style='color: red;' > "+ data.msg +" </strong>" );
                        removeMsg();
                    }

                }
            );

        }

        function removeMsg(){
            setTimeout(function(){
                $("#isValidCodeOrNot").empty();
            }, 2000);
        }
		
	$(document).ready(function(){
		var restricted = $('#restricted_item').val();
		if(restricted != null){
			for(var i in restricted) {
				$("#specific_item option[value='"+restricted[i]+"']").prop('disabled', true);
			}
			$('#specific_item').select2();
		}
		
		var specific = $('#specific_item').val();
		if(specific != null){
			for(var i in specific) {
				$("#restricted_item option[value='"+specific[i]+"']").prop('disabled', true);
			}
			$('#restricted_item').select2();
		}
	});

	$('#restricted_item').change(function () {
		var selected = $(this).val();
		$.map($('#specific_item option'), function(ele) {
			$("#specific_item option[value='" + ele.value + "']").prop("disabled", false);
		});
		if(selected != null){
			for(var i in selected) {
				$("#specific_item option[value='"+selected[i]+"']").prop('disabled', true);
			}
		}
		$('#specific_item').select2();
		
	});

	$('#specific_item').change(function () {
		var selected = $(this).val();
		$.map($('#restricted_item option'), function(ele) {
			$("#restricted_item option[value='" + ele.value + "']").prop("disabled", false);
		});

		if(selected != null){
			for(var i in selected) {
				$("#restricted_item option[value='"+selected[i]+"']").prop('disabled', true);
			}
		}
		$('#restricted_item').select2();
	});
	
	$('#type').change(function () {
		var selected = $(this).val();
		if(selected=='fixed'){
			$('.Discountlabel').html('Offer Maximum Discount ( &#8377; )');
		}else{
			$('.Discountlabel').html('Offer Maximum Discount ( % )');
		}
	});

    </script>
@endpush

resources/views/admin/offers/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Manage Offer</h4>
                <p class="card-category">List of Offers</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <div class="gapMe" >
                    <a href="{{route('admin.offers.create')}}" class="btn btn-primary float-right">Add New</a>
                  </div>
                  <table class="tableRouteManager">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>Offer Name</th>
                      <th>Description</th>
                      <th>Type</th>
                      <th>code</th>
                      <th>Start Date</th>
                      <th>Expiry Date</th>
                      <th>Min Package Amount</th>
                      <th>Max Discount</th>
{{--                      <th>Specific Item</th>--}}
{{--                      <th>Restricted Item</th>--}}

                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  $(document).ready(function() {
    $('.tableRouteManager').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.offers') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'description', name: 'description'},
            {data: 'type', name: 'type'},
            {data: 'code', name: 'code'},
            {data: 'start_date', name: 'start_date'},
            {data: 'expiry_date', name: 'expiry_date'},
            {data: 'min_package_amount', name: 'min_package_amount'},
            {data: 'max_discount', name: 'max_discount'},
            // {data: 'specific_item', name: 'specific_item'},
            // {data: 'restricted_item', name: 'restricted_item'},
            {{--{data: 'specific_item', name: 'specific_item',render: function( data, type, full, meta ) { return "<img src='"+ "{{asset('sliders')}}/" + data + "' height='50'/>"; }},--}}

            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true,
            },
        ]
    });
  } );

  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableRouteManager').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      }).then(function(){
                          $(e).closest("tr").remove();
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }
</script>
@endpush