routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//https://tutsforweb.com/how-to-set-up-task-scheduling-cron-job-in-laravel/
//https://stackoverflow.com/questions/49921916/notify-users-if-their-account-is-going-to-expire-in-5-days-later-laravel
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// die('ddd');
Route::get('/routes', function () {
    $routesname = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->getName();
      });
    $routesuri = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->uri();
      });
    echo"<pre>";print_r($routesname);
    echo"<pre>";print_r($routesuri);
    die;
});

Auth::routes();

Route::get('admin/login', function () {
    return view('auth.login');
});
Route::get('alert', 'AlertController@index')->name('packageAlert');
Route::get('/', 'HomeController@index')->name('homepage');
Route::get('/hosting', 'HomeController@hosting')->name('hosting');
Route::get('plan/configure/{id}', 'HomeController@planConfigure')->name('plan.configure');
Route::get('/about/us', 'HomeController@about')->name('about');
Route::get('/contact/us', 'HomeController@contactUs')->name('contact.us');
Route::post('/save/contact/us', 'HomeController@saveContactDetail')->name('save.contact.detail');
Route::get('/new', 'HomeController@theme');

Route::get('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofile');
Route::post('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofilepost');
Route::get('/userorder', 'UsersprofileController@userOrder')->name('userOrder');

Route::get('home', 'HomeController@index')->name('home');
Route::get('/cart', 'CartController@index')->name('cart');
Route::post('apply/code', 'CartController@applyCode')->name('apply.code');
Route::get('/add-cart/{id}', 'CartController@addcart')->name('addcart');
Route::get('/cart-delete/{id}', 'CartController@deletecart')->name('deletecart');

Route::group(['middleware' =>'auth'], function () {
    Route::get('/checkout', 'CartController@checkout')->name('checkout');
    Route::get('/payment/{payment_method}', 'CartController@checkoutPost')->name('Payment');
    Route::get('/paypalpaymentcancel', 'CartController@paymentCancel')->name('paymentCancel');
    Route::get('/paymentsuccess', 'CartController@paymentSuccess')->name('paymentSuccess');
    Route::post('/razorpaysuccess', 'CartController@razorpaySuccess')->name('razorpaysuccess');
});

Route::get('/remindertousers', 'HomeController@remindertousers')->name('remindertousers');


// Route::group(['middleware' => 'user_permission'], function () {
//     Route::resource('hostings', 'HostingsController');
// });

Route::group(['middleware' => ['user_permission'],'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'name'=>'admin.'], function() {

        Route::get('hostings/about/to/expire/', 'HostingMonitorController@listHostingsABoutToExpire')->name('about.to.expire');
        Route::get('todays/sale', 'HostingMonitorController@todaysSale')->name('todays.sale');

        Route::get('sale/overview/{id}', 'HostingMonitorController@saleOverview')->name('sale.overview');
        Route::get('hosting/overview/{id}', 'HostingMonitorController@saleOverview')->name('hosting.overview');


        //dashboard
    	Route::get('/', 'HomeController@index')->name('home');

    	//hostings routes
    	Route::resource('hostings', 'HostingsController');


    	//users routes
    	Route::resource('users', 'UsersController');
        Route::get('user/roles', 'UsersController@UserRoles')->name('UserRoles');
    	Route::get('adduser/role', 'UsersController@Addrole')->name('addrole');
        Route::post('adduser/role', 'UsersController@Addrole')->name('addrolepost');
        Route::get('edituser/role/{id}', 'UsersController@Editrole')->name('editrole');
        Route::post('edituser/role/{id}', 'UsersController@Editrole')->name('editrolepost');
        Route::DELETE('deleteuser/role/{id}', 'UsersController@destroyUserRole')->name('destroyUserRole');
        Route::get('user/permission', 'UserPermissionsController@index');

        //addon routes
        Route::resource('addons','AddonController');

    	//orders routes
    	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
    	Route::get('/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
    	Route::post('/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');

        
        // routes manager
        Route::resource('routesmanager', 'RoutesmanagerController');
        

        Route::get('slider/list', 'SliderController@index')->name('sliders');
        Route::get('create/slider', 'SliderController@create')->name('slider.create');
        Route::post('save/slider', 'SliderController@store')->name('slider.save');

        Route::any('delete/slider/{id}', 'SliderController@destroy')->name('slider.delete');

        Route::get('edit/slider/{id}', 'SliderController@edit')->name('slider.edit');
        Route::any('update/slider/{id}', 'SliderController@update')->name('slider.update');


        Route::get('feature/list', 'FeatureController@index')->name('features');
        Route::get('create/feature', 'FeatureController@create')->name('feature.create');
        Route::post('save/feature', 'FeatureController@store')->name('feature.save');

        Route::any('delete/feature/{id}', 'FeatureController@destroy')->name('feature.delete');

        Route::get('edit/feature/{id}', 'FeatureController@edit')->name('feature.edit');
        Route::any('update/feature/{id}', 'FeatureController@update')->name('feature.update');

        //offers
        Route::get('offers/list', 'OffersController@index')->name('offers');
        Route::get('create/offers', 'OffersController@create')->name('offers.create');
        Route::post('save/offers', 'OffersController@save')->name('offers.save');

        Route::get('edit/offers/{id}', 'OffersController@edit')->name('offers.edit');
        Route::any('delete/offers/{id}', 'OffersController@destroy')->name('offers.delete');
        Route::any('delete/update/{id}', 'OffersController@update')->name('offers.update');
        Route::post('check/valid/offer/code', 'OffersController@checkValidOfferCode')->name('check.valid.offer.code');

        //contact module
        Route::get('contact/list', 'ContactController@index')->name('contact.list');
        Route::any('delete/contact/{id}', 'ContactController@destroy')->name('contact.delete');

        Route::get('contact/page/detail', 'ContactController@ContactPageDetail')->name('contact.page.detail');
        Route::post('save/contact/page/detail', 'ContactController@saveContactPageDetail')->name('save.contact.page.detail');


    });
});

app/Models/Feature.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Validator;
use Illuminate\Support\Facades\Storage;
use Auth;
use File;

class Feature extends Model
{
    
    protected $fillable = ["user_id", "image", "title",'description'];
    protected $table = "features";
    protected $primaryKey = "id";


    public function saveFeatureDetails($inputs=null,$imageName=null){

    	$data = $inputs->except(['_token']);

    	$data['user_id'] = Auth::user()->id;
    	$data['image'] = $imageName;

    	Feature::Create($data);
    }

    
    function saveFeatureImage($image=null){


    	$random_number = mt_rand(1000, 9999);
	    $imgName = str_replace(' ', '', $random_number."_".$image->getClientOriginalName());

    	Storage::disk('forfeatures')->put($imgName, file_get_contents($image->getRealPath()));

    	return $imgName;
	}	


    public function validateSliderDetails($request){

        return $validator = Validator::make($request->all(), [

            'title'=>'required|string',
            'description'=>'required|string',
            'image'=>'required|image|mimes:jpeg,png,jpg|max:2048',
        ]);

    }

    public function validateFeatureUpdateDetails($request){

        return $validator = Validator::make($request->all(), [

            'title'=>'required|string',
            'description'=>'required|string',
        ]);

    }

    public function updateFeature($inputs=null,$id=null,$imageName=null){

    	if($imageName!=null){
    		$imageName = $imageName;
    	}else{
    		$imageName = Feature::where('id',$id)->pluck('image')->first();
    	}

    	$data = $inputs->except(['_token','_method']);

    	$data['user_id'] = Auth::user()->id;
    	$data['image']   = $imageName;

    	Feature::where('id', $id)->update($data);
    }

}

app/Http/Controllers/Admin/FeatureController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use App\Models\Slider;
use App\Models\User;
use File;

use App\Models\Feature;

class FeatureController extends Controller

{

	public function index(Request $request){
    	
        if ($request->ajax()) {

            $data = Feature::latest()->get();

            	return DataTables::of($data)->addColumn('action', function($data){

                    $edit = route('admin.feature.edit',$data->id);
                    $delete = route('admin.feature.delete',$data->id);
                    $button = '<a name="edit" id="'.$data->id.'" class="edit btn btn-primary btn-sm" href="'.$edit.'">Edit</a>';
                    $button .= '&nbsp;&nbsp;&nbsp;<button type="button" class="delete btn btn-danger btn-sm" onclick="deleteData(this)" data-id="'.$data->id.'" data-url="'.$delete.'">Delete</button>';

                    return $button;

                })->rawColumns(['action'])->make(true);

        }

        return view('admin.feature.index');

    }


    public function create(){

        return view('admin.feature.addoredit');
    }



    public function store(Request $request){

    	$validation = (new Feature)->validateSliderDetails($request);

        if($validation->fails()) {

         	return back()->withErrors($validation);
        }
        try
        {

            \DB::beginTransaction();
                


	            $imageName = (new Feature)->saveFeatureImage($request->File('image'));

	            (new Feature)->saveFeatureDetails($request,$imageName);

            \DB::commit();

            return back()->with('success','Added successfully');


        }
        catch (\Exception $e)
        {
            \DB::rollBack();
            return back()->with('error','Something Wrong');
        }	

    }



    public function edit($id=null){   

        $route = Feature::find($id);

        return view('admin.feature.addoredit',compact('route'));

    }




    public function update(Request $request, $id=null){

    	$validation = (new Feature)->validateFeatureUpdateDetails($request);

        if($validation->fails()) {

         	return back()->withErrors($validation);
        }
        try
        {
            \DB::beginTransaction();

            if($request->hasFile('image')){
            	$imageName = (new Feature)->saveFeatureImage($request->File('image'));
            }else{
            	$imageName = null;
            }

            (new Feature)->updateFeature($request,$id,$imageName);

            \DB::commit();

            return back()->with('success','Updated successfully');


        }
        catch (\Exception $e)
        {
            \DB::rollBack();
            return back()->with('error','Something Wrong');
        }


    }



    public function destroy($id=null){
        
        $response = Feature::where('id',$id)->delete();
            
            if($response){

                return true;
            }else{

                return false;
            }
    }

}

?>

resources/views/admin/feature/addoredit.blade.php
@extends('admin.layouts.app')
<style type="text/css"> img { display: block; max-width:180px; max-height:180px; width: auto; height: auto; } </style>
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">




            <div class="card">
              <div class="card-header card-header-primary">
                @if(isset($route))
                    <h4 class="card-title ">Update Features</h4>
                @else
                    <h4 class="card-title ">Create Features</h4>
                @endif

              </div>
              <div class="card-body">
                
                  


                  @if(isset($route))
                    {{ Form::model($route, ['route' => ['admin.feature.update', $route->id], 'method' => 'patch','files'=>'true']) }}
                  @else
                      {{ Form::open(['route' => 'admin.feature.save','files'=>'true']) }}
                  @endif

                  <div class="row">
                    <div class="  col-md-12">
                      <label for="title" class="col-form-label">Title</label>
                        {{ Form::text('title',null,['class'=>'form-control','id'=>'title']) }}
                        @if($errors->has('title'))
                            <div class="error">{{ $errors->first('title') }}</div>
                        @endif
                    </div>
                    
                  </div>

                    <div class="row">
                        <div class=" col-md-12">
                            <label for="description" class="col-form-label">Text Here</label>
                            {{ Form::textarea('description',null,['class'=>'form-control','id'=>'description','rows'=>'4', 'cols'=>'200']) }}
                            @if($errors->has('description'))
                                <div class="error">{{ $errors->first('description') }}</div>
                            @endif
                        </div> 
                    </div>

                 
                    <div class="row">
                        <div class=" col-md-12">
                            <label for="image" class="col-form-label">Slider Image</label>

                        </div>
                    </div>

                    {{Form::file('image',null,['class'=>'form-control'])}}
                    @if($errors->has('image'))
                        <div class="error">{{ $errors->first('image') }}</div>
                    @endif
                    
                    @if(!empty($route->image))
                      <div class="row">
                        <div class=" col-md-12 " style="height: 28%">
                            <img width="400" height="400" src="{{ asset('features') }}/{{$route->image}}">
                        </div>
                      </div>
                    @endif
                    
                  <div class="row">
                    <div class="form-group col-md-6">
                       {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
                    </div>
                  </div>
              </form>



                
              </div>
            </div>



          </div>
        </div>
      </div>
  </div>
</div>
@endsection

@push('scripts')
@endpush

resources/views/admin/feature/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Features Manager</h4>
                <p class="card-category">List of Features</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <div class="gapMe" >
                  <a href="{{route('admin.feature.create')}}" class="btn btn-primary float-right">Add New</a>
                  </div>
                  <table class="tableRouteManager">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>Feature Logo</th>
                      <th>Title</th>
                      <th>Description</th>
                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  $(document).ready(function() {
    $('.tableRouteManager').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.features') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'image', name: 'image',render: function( data, type, full, meta ) { return "<img src='"+ "{{asset('features')}}/" + data + "' height='50'/>"; }},
            {data: 'title', name: 'title'},
            {data: 'description', name: 'description'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true,
            },
        ]
    });
  } );



  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableRouteManager').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      }).then(function(){
                          $(e).closest("tr").remove();
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }
</script>
@endpush