routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//https://tutsforweb.com/how-to-set-up-task-scheduling-cron-job-in-laravel/
//https://stackoverflow.com/questions/49921916/notify-users-if-their-account-is-going-to-expire-in-5-days-later-laravel
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// die('ddd');
Route::get('/routes', function () {
    $routesname = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->getName();
      });
    $routesuri = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->uri();
      });
    echo"<pre>";print_r($routesname);
    echo"<pre>";print_r($routesuri);
    die;
});

Auth::routes();

Route::get('admin/login', function () {
    return view('auth.login');
});
Route::get('alert', 'AlertController@index')->name('packageAlert');
Route::get('/', 'HomeController@index')->name('homepage');
Route::get('/hosting', 'HomeController@hosting')->name('hosting');
Route::get('plan/configure/{id}', 'HomeController@planConfigure')->name('plan.configure');
Route::get('/about/us', 'HomeController@about')->name('about');
Route::get('/contact/us', 'HomeController@contactUs')->name('contact.us');
Route::post('/save/contact/us', 'HomeController@saveContactDetail')->name('save.contact.detail');
Route::get('/new', 'HomeController@theme');

Route::get('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofile');
Route::post('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofilepost');
Route::get('/userorder', 'UsersprofileController@userOrder')->name('userOrder');

Route::get('home', 'HomeController@index')->name('home');
Route::get('/cart', 'CartController@index')->name('cart');
Route::post('apply/code', 'CartController@applyCode')->name('apply.code');
Route::get('/add-cart/{id}', 'CartController@addcart')->name('addcart');
Route::get('/cart-delete/{id}', 'CartController@deletecart')->name('deletecart');

Route::group(['middleware' =>'auth'], function () {
    Route::get('/checkout', 'CartController@checkout')->name('checkout');
    Route::get('/payment/{payment_method}', 'CartController@checkoutPost')->name('Payment');
    Route::get('/paypalpaymentcancel', 'CartController@paymentCancel')->name('paymentCancel');
    Route::get('/paymentsuccess', 'CartController@paymentSuccess')->name('paymentSuccess');
    Route::post('/razorpaysuccess', 'CartController@razorpaySuccess')->name('razorpaysuccess');
});

Route::get('/remindertousers', 'HomeController@remindertousers')->name('remindertousers');


// Route::group(['middleware' => 'user_permission'], function () {
//     Route::resource('hostings', 'HostingsController');
// });

Route::group(['middleware' => ['user_permission'],'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'name'=>'admin.'], function() {

        Route::get('hostings/about/to/expire/', 'HostingMonitorController@listHostingsABoutToExpire')->name('about.to.expire');
        Route::get('todays/sale', 'HostingMonitorController@todaysSale')->name('todays.sale');

        Route::get('sale/overview/{id}', 'HostingMonitorController@saleOverview')->name('sale.overview');
        Route::get('hosting/overview/{id}', 'HostingMonitorController@saleOverview')->name('hosting.overview');


        //dashboard
    	Route::get('/', 'HomeController@index')->name('home');

    	//hostings routes
    	Route::resource('hostings', 'HostingsController');


    	//users routes
    	Route::resource('users', 'UsersController');
        Route::get('user/roles', 'UsersController@UserRoles')->name('UserRoles');
    	Route::get('adduser/role', 'UsersController@Addrole')->name('addrole');
        Route::post('adduser/role', 'UsersController@Addrole')->name('addrolepost');
        Route::get('edituser/role/{id}', 'UsersController@Editrole')->name('editrole');
        Route::post('edituser/role/{id}', 'UsersController@Editrole')->name('editrolepost');
        Route::DELETE('deleteuser/role/{id}', 'UsersController@destroyUserRole')->name('destroyUserRole');
        Route::get('user/permission', 'UserPermissionsController@index');

        //addon routes
        Route::resource('addons','AddonController');

    	//orders routes
    	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
    	Route::get('/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
    	Route::post('/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');

        
        // routes manager
        Route::resource('routesmanager', 'RoutesmanagerController');
        

        Route::get('slider/list', 'SliderController@index')->name('sliders');
        Route::get('create/slider', 'SliderController@create')->name('slider.create');
        Route::post('save/slider', 'SliderController@store')->name('slider.save');

        Route::any('delete/slider/{id}', 'SliderController@destroy')->name('slider.delete');

        Route::get('edit/slider/{id}', 'SliderController@edit')->name('slider.edit');
        Route::any('update/slider/{id}', 'SliderController@update')->name('slider.update');


        Route::get('feature/list', 'FeatureController@index')->name('features');
        Route::get('create/feature', 'FeatureController@create')->name('feature.create');
        Route::post('save/feature', 'FeatureController@store')->name('feature.save');

        Route::any('delete/feature/{id}', 'FeatureController@destroy')->name('feature.delete');

        Route::get('edit/feature/{id}', 'FeatureController@edit')->name('feature.edit');
        Route::any('update/feature/{id}', 'FeatureController@update')->name('feature.update');

        //offers
        Route::get('offers/list', 'OffersController@index')->name('offers');
        Route::get('create/offers', 'OffersController@create')->name('offers.create');
        Route::post('save/offers', 'OffersController@save')->name('offers.save');

        Route::get('edit/offers/{id}', 'OffersController@edit')->name('offers.edit');
        Route::any('delete/offers/{id}', 'OffersController@destroy')->name('offers.delete');
        Route::any('delete/update/{id}', 'OffersController@update')->name('offers.update');
        Route::post('check/valid/offer/code', 'OffersController@checkValidOfferCode')->name('check.valid.offer.code');

        //contact module
        Route::get('contact/list', 'ContactController@index')->name('contact.list');
        Route::any('delete/contact/{id}', 'ContactController@destroy')->name('contact.delete');

        Route::get('contact/page/detail', 'ContactController@ContactPageDetail')->name('contact.page.detail');
        Route::post('save/contact/page/detail', 'ContactController@saveContactPageDetail')->name('save.contact.page.detail');


    });
});

resources/views/admin/hostings_about_to_expire/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Upcoming Hosting Expiry</h4>
                <p class="card-category"> List of Hostings</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  {{--<a href="{{route('admin.orders.create')}}" class="btn btn-primary">Add New</a>--}}
                  <!-- <div class="form-group">
                    <label for="sel1">Select Status:</label>
                    <select class="form-control" id="selectstatus">
                      <option value="process">Process</option>
                      <option value="completed">Completed</option>
                      <option value="cancel">Cancel</option>
                    </select>
                  </div> -->
                  <table class="tableHosting">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>User Name</th>
                      <th>User Email</th>
                      <th>Amount</th>
                      <th>Will Expired In (days) </th>
                      <th>Transaction ID</th>
                      <th>Start Date</th>
                      <th>End Date</th>
                      <th>Status</th>
                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection


@push('scripts')

<script type="text/javascript">
  
  	$(document).ready(function() {
    $('.tableHosting').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ url('admin/hostings/about/to/expire/') }}",

        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'sub_total', name: 'sub_total'},
            {data: 'leftDays', name: 'leftDays'},
            {data: 'payment_id', name: 'payment_id'},
            {data: 'activation_date', name: 'activation_date'},
            {data: 'expire_date', name: 'expire_date'},
            {data: 'status', name: 'status'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },

        ]

    });

  } );



  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableHosting').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      },
                      function(){ 
                          location.reload();
                          table.row($(e).parents('tr')).remove().draw(false);
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }
</script>

@endpush

resources/views/admin/hostings_about_to_expire/orderview.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="container-fluid my-5 d-flex justify-content-center">
    <div class="card card-1">
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h6 class="color-1 mb-0 change-color">List of Plan</h6>
                </div>
            </div>
            
            <div class="row">
                <div class="col">
                    <div class="card card-2">
                        <div class="card-body">
                            <div class="media">
                                
                                <div class="media-body my-auto text-right">
                                    <div class="row my-auto flex-column flex-md-row">
                                        <div class="col my-auto">
                                            <h6 class="mb-0">{{ $item->item_name}}</h6>
                                        </div>
                                        <div class="col my-auto"> 
                                            <h6 class="mb-0">&#8377;{{ $item->item_price}}</h6>
                                        </div>
                                        <div class="col my-auto"> 
                                            <h6>
                                                <?php
                                                    if($item->duration == '2'){
                                                        echo "year";
                                                    }

                                                    if($item->duration == '1'){
                                                        echo "month";
                                                    }
                                                ?>
                                            </h6>
                                        </div>
                                        <div class="col my-auto">
                                            @if($item->status == 'process')
                                            <button type="button" id="test1" class="btn btn-info btn-sm process" data-id="{{$item->id}}" data-username="{{$item->username}}" data-domain="{{$item->domain}}" data-password="{{$item->password}}" data-massage ="{{$item->massage}}" data-email="{{$item->email}}" data-toggle="modal" data-target="#myModal">Process<div class="ripple-container"></div></button>
                                            @elseif($item->status == 'completed')
                                            <button type="button" id="test1" class="btn btn-basic btn-sm process" data-id="{{$item->id}}" data-username="{{$item->username}}" data-domain="{{$item->domain}}" data-password="{{$item->password}}" data-massage ="{{$item->massage}}" data-email="{{$item->email}}" data-toggle="modal" data-target="#myModal">Completed<div class="ripple-container"></div></button>
                                            @else
                                            @endif
                                        </div>
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row mt-4">
                <div class="col">
                    <div class="row justify-content-between">
                        <div class="col-auto">
                            <p class="mb-1 text-dark"><b>Order Details</b></p>
                        </div>
                        <div class="flex-sm-col text-right col">
                            <p class="mb-1"><b>Plan Price</b></p>
                        </div>
                        <div class="flex-sm-col col-auto">
                            <p class="mb-1">&#8377;{{$item->item_price}}</p>
                        </div>
                    </div>
                    <div class="row justify-content-between">
                        <div class="flex-sm-col text-right col">
                            <p class="mb-1"> <b>Discount (%)</b></p>
                        </div>
                        <div class="flex-sm-col col-auto">
                            <p class="mb-1">
                                @if(!empty($item->discountRate))
                                    {{ $item->discountRate }}
                                @else
                                    {{ __('0') }}
                                @endif
                            </p>
                        </div>
                    </div>
                    <div class="row justify-content-between">
                        <div class="flex-sm-col text-right col">
                            <p class="mb-1"><b>TAX (%)</b></p>
                        </div>
                        <div class="flex-sm-col col-auto">
                            <p class="mb-1">
                                @if(!empty($item->taxrate))
                                    {{$item->taxrate}}
                                @else
                                    {{ __('0') }}
                                @endif
                            </p>
                        </div>
                    </div>

                    <!-- <div class="row justify-content-between">
                        <div class="flex-sm-col text-right col">
                            <p class="mb-1"><b>Delivery Charges</b></p>
                        </div>
                        <div class="flex-sm-col col-auto">
                            <p class="mb-1">Free</p>
                        </div>
                    </div> -->

                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="jumbotron-fluid">
                <div class="row justify-content-between ">
                    <div class="col-auto my-auto ">
                        <h2 class="mb-0 font-weight-bold">TOTAL PAID</h2>
                    </div>
                    <div class="col-auto my-auto ml-auto">
                        <h1 class="display-3 ">&#8377; {{$item->total_price}}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Modal -->
          <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title">Send Hosting Credentials</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <form method="post" action="{{route('admin.orderprocess')}}">
                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="orderid" id="orderid" value="">
                  <div class="">
                    <label for="useremail" class="col-form-label">Email address</label>
                    <input type="email" class="form-control" id="useremail" name="email" >
                  </div>
                  <div class="">
                    <label for="domain" class="col-form-label" >Domain</label>
                    <input type="text" class="form-control" id="domain" name="domain" >
                  </div>
                  <div class="">
                    <label for="username" class="col-form-label" >Username</label>
                    <input type="text" class="form-control" id="username" name="username" >
                  </div>
                  <div class="">
                    <label for="password" class="col-form-label" >Password</label>
                    <input type="text" class="form-control" id="password" name="password" >
                  </div>
                  <div class="">
                    <label for="massage" class="col-form-label" >Massage</label>
                    <textarea class="form-control" id="massage" name="massage" rows="3"></textarea>
                  </div>
                  <!-- <div class="form-group">
                    <input type="submit" name="submit" class="form-control">
                  </div> -->
                </div>
                <div class="modal-footer">
                    <button type="submit" name="submit" class="btn btn-info">Submit</button>
                 <!--  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
                </div>
                </form>
              </div>
            </div>
          </div>
@endsection

@push('scripts')
<script src="{{ asset('dashboard/assets/js/tinymce.min.js') }}" referrerpolicy="origin"></script>
<script>
      tinymce.init({
        selector: 'textarea#message',
        menubar: false
      });

    $(document.body).on('click', '.process', function(event) {
        $('#useremail').val($(this).data('email'));
        $('#orderid').val($(this).data('id'));
        $('#password').val($(this).data('password'));
        $('#domain').val($(this).data('domain'));
        $('#username').val($(this).data('username'));
        $('#massage').val($(this).data('massage'));
    });
</script>
@endpush

resources/views/admin/hostings_about_to_expire/todaysSale.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Today's Sale</h4>
                <p class="card-category"> List of todays sale</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  {{--<a href="{{route('admin.orders.create')}}" class="btn btn-primary">Add New</a>--}}
                  <!-- <div class="form-group">
                    <label for="sel1">Select Status:</label>
                    <select class="form-control" id="selectstatus">
                      <option value="process">Process</option>
                      <option value="completed">Completed</option>
                      <option value="cancel">Cancel</option>
                    </select>
                  </div> -->
                  <table class="tableHosting">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>User Name</th>
                      <th>User Email</th>
                      <th>Amount (&#8377;)</th>
                      <th>Payment Status</th>
                      <th>Transaction ID</th>
                      <th>Start Date</th>
                      <th>End Date</th>
                      <th>Status</th>
                      <th>Date</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection


@push('scripts')

<script type="text/javascript">
  
  	$(document).ready(function() {
    $('.tableHosting').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ url('admin/todays/sale') }}",

        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'sub_total', name: 'sub_total'},
            {data: 'payment_status', name: 'payment_status'},
            {data: 'payment_id', name: 'payment_id'},
            {data: 'activation_date', name: 'activation_date'},
            {data: 'expire_date', name: 'expire_date'},
            {data: 'status', name: 'status'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },

        ]

    });

  } );



  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });

</script>

@endpush