routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//https://tutsforweb.com/how-to-set-up-task-scheduling-cron-job-in-laravel/
//https://stackoverflow.com/questions/49921916/notify-users-if-their-account-is-going-to-expire-in-5-days-later-laravel
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// die('ddd');
Route::get('/routes', function () {
    $routesname = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->getName();
      });
    $routesuri = (array)collect(\Route::getRoutes())->map(function ($route) {
     return $route->uri();
      });
    echo"<pre>";print_r($routesname);
    echo"<pre>";print_r($routesuri);
    die;
});

Auth::routes();

Route::get('admin/login', function () {
    return view('auth.login');
});
Route::get('alert', 'AlertController@index')->name('packageAlert');
Route::get('/', 'HomeController@index')->name('homepage');
Route::get('/hosting', 'HomeController@hosting')->name('hosting');
Route::get('plan/configure/{id}', 'HomeController@planConfigure')->name('plan.configure');
Route::get('/about/us', 'HomeController@about')->name('about');
Route::get('/contact/us', 'HomeController@contactUs')->name('contact.us');
Route::post('/save/contact/us', 'HomeController@saveContactDetail')->name('save.contact.detail');
Route::get('/new', 'HomeController@theme');

Route::get('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofile');
Route::post('/profile', 'UsersprofileController@Viewprofile')->name('Viewprofilepost');
Route::get('/userorder', 'UsersprofileController@userOrder')->name('userOrder');

Route::get('home', 'HomeController@index')->name('home');
Route::get('/cart', 'CartController@index')->name('cart');
Route::post('apply/code', 'CartController@applyCode')->name('apply.code');
Route::get('/add-cart/{id}', 'CartController@addcart')->name('addcart');
Route::get('/cart-delete/{id}', 'CartController@deletecart')->name('deletecart');

Route::group(['middleware' =>'auth'], function () {
    Route::get('/checkout', 'CartController@checkout')->name('checkout');
    Route::get('/payment/{payment_method}', 'CartController@checkoutPost')->name('Payment');
    Route::get('/paypalpaymentcancel', 'CartController@paymentCancel')->name('paymentCancel');
    Route::get('/paymentsuccess', 'CartController@paymentSuccess')->name('paymentSuccess');
    Route::post('/razorpaysuccess', 'CartController@razorpaySuccess')->name('razorpaysuccess');
});

Route::get('/remindertousers', 'HomeController@remindertousers')->name('remindertousers');


// Route::group(['middleware' => 'user_permission'], function () {
//     Route::resource('hostings', 'HostingsController');
// });

Route::group(['middleware' => ['user_permission'],'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'name'=>'admin.'], function() {

        Route::get('hostings/about/to/expire/', 'HostingMonitorController@listHostingsABoutToExpire')->name('about.to.expire');
        Route::get('todays/sale', 'HostingMonitorController@todaysSale')->name('todays.sale');

        Route::get('sale/overview/{id}', 'HostingMonitorController@saleOverview')->name('sale.overview');
        Route::get('hosting/overview/{id}', 'HostingMonitorController@saleOverview')->name('hosting.overview');


        //dashboard
    	Route::get('/', 'HomeController@index')->name('home');

    	//hostings routes
    	Route::resource('hostings', 'HostingsController');


    	//users routes
    	Route::resource('users', 'UsersController');
        Route::get('user/roles', 'UsersController@UserRoles')->name('UserRoles');
    	Route::get('adduser/role', 'UsersController@Addrole')->name('addrole');
        Route::post('adduser/role', 'UsersController@Addrole')->name('addrolepost');
        Route::get('edituser/role/{id}', 'UsersController@Editrole')->name('editrole');
        Route::post('edituser/role/{id}', 'UsersController@Editrole')->name('editrolepost');
        Route::DELETE('deleteuser/role/{id}', 'UsersController@destroyUserRole')->name('destroyUserRole');
        Route::get('user/permission', 'UserPermissionsController@index');

        //addon routes
        Route::resource('addons','AddonController');

    	//orders routes
    	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
    	Route::get('/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
    	Route::post('/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');

        
        // routes manager
        Route::resource('routesmanager', 'RoutesmanagerController');
        

        Route::get('slider/list', 'SliderController@index')->name('sliders');
        Route::get('create/slider', 'SliderController@create')->name('slider.create');
        Route::post('save/slider', 'SliderController@store')->name('slider.save');

        Route::any('delete/slider/{id}', 'SliderController@destroy')->name('slider.delete');

        Route::get('edit/slider/{id}', 'SliderController@edit')->name('slider.edit');
        Route::any('update/slider/{id}', 'SliderController@update')->name('slider.update');


        Route::get('feature/list', 'FeatureController@index')->name('features');
        Route::get('create/feature', 'FeatureController@create')->name('feature.create');
        Route::post('save/feature', 'FeatureController@store')->name('feature.save');

        Route::any('delete/feature/{id}', 'FeatureController@destroy')->name('feature.delete');

        Route::get('edit/feature/{id}', 'FeatureController@edit')->name('feature.edit');
        Route::any('update/feature/{id}', 'FeatureController@update')->name('feature.update');

        //offers
        Route::get('offers/list', 'OffersController@index')->name('offers');
        Route::get('create/offers', 'OffersController@create')->name('offers.create');
        Route::post('save/offers', 'OffersController@save')->name('offers.save');

        Route::get('edit/offers/{id}', 'OffersController@edit')->name('offers.edit');
        Route::any('delete/offers/{id}', 'OffersController@destroy')->name('offers.delete');
        Route::any('delete/update/{id}', 'OffersController@update')->name('offers.update');
        Route::post('check/valid/offer/code', 'OffersController@checkValidOfferCode')->name('check.valid.offer.code');

        //contact module
        Route::get('contact/list', 'ContactController@index')->name('contact.list');
        Route::any('delete/contact/{id}', 'ContactController@destroy')->name('contact.delete');

        Route::get('contact/page/detail', 'ContactController@ContactPageDetail')->name('contact.page.detail');
        Route::post('save/contact/page/detail', 'ContactController@saveContactPageDetail')->name('save.contact.page.detail');


    });
});

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;
use App\Models\ContactDetail;
use Illuminate\Http\Request;
use App\Models\ContactUs;
use App\Models\Slider;
use App\Models\User;
use File;
use Auth;


class ContactController extends Controller

{

    public function index(Request $request){

        if ($request->ajax()) {

            $data = ContactUs::latest()->get();

            return DataTables::of($data)->addColumn('action', function($data){

//                $edit = route('admin.slider.edit',$data->id);
                $delete = route('admin.contact.delete',$data->id);
//                $button = '<a name="edit" id="'.$data->id.'" class="edit btn btn-primary btn-sm" href="'.$edit.'">Edit</a>';
                $button = '&nbsp;&nbsp;&nbsp;<button type="button" class="delete btn btn-danger btn-sm" onclick="deleteData(this)" data-id="'.$data->id.'" data-url="'.$delete.'">Delete</button>';

                return $button;

            })->rawColumns(['action'])->make(true);

        }
        return view('admin.contact.index');
    }

    public function destroy($id=null){
        $response = ContactUs::find($id);
        if($response->delete()){
            return true;
        }else{
            return false;
        }
    }

    public function getAdminId(){
        return User::where('is_admin',1)->pluck('id')->first();
    }

    public function ContactPageDetail(){

        $data = ContactDetail::where('user_id',$this->getAdminId())->first();
        return view('admin.contact.addoredit',compact('data'));
    }

    public function saveContactPageDetail(Request $request){
        $rules = array(
            'phone' => 'required|numeric',
            'email' => 'required|email',
            'website' => 'required|string',
            'address' => 'required|string',
        );

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return back()->withInput()->withErrors($validator);
        }else{

            $data = [
                'phone' => $request->phone,
                'email' => $request->email,
                'website' => $request->website,
                'address' => $request->address,
            ];

            ContactDetail::updateOrCreate( [ 'id' => $request->id ],$data);

//            $res = ContactDetail::where('id',$request->id)->update($data);

            return back()->with('success','Contact detail has been successfully updated');
        }
    }




}
?>

resources/views/admin/contact/addoredit.blade.php
@extends('admin.layouts.app')
<style type="text/css"> img { display: block; max-width:180px; max-height:180px; width: auto; height: auto; } </style>
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">

            <div class="card">
                <div class="card-header card-header-primary">
                      <h4 class="card-title ">Update Contact Details</h4>
                </div>
                    <div class="card-body">

{{--                        @if(isset($route))--}}
                        {{ Form::model($data, ['route' => ['admin.save.contact.page.detail'], 'method' => 'post','files'=>'true']) }}
{{--                        @else--}}
{{--                            {{ Form::open(['route' => 'admin.slider.save','files'=>'true']) }}--}}
{{--                        @endif--}}

                        <div class="row">

                          <div class=" col-md-4">
                            <label for="phone" class="col-form-label">Phone Number</label>
                              {{ Form::text('phone',null,['class'=>'form-control','id'=>'heading_first']) }}
                              @if($errors->has('phone'))
                                  <div class="error" style="color: red;" >{{ $errors->first('phone') }}</div>
                              @endif
                          </div>

                          <div class=" col-md-4">
                            <label for="heading_second" class="col-form-label">Email Address</label>
                            {{ Form::email('email',null,['class'=>'form-control','id'=>'heading_second']) }}
                            @if($errors->has('email'))
                                <div class="error" style="color: red;" >{{ $errors->first('email') }}</div>
                            @endif
                          </div>
                            <div class=" col-md-4">
                                <label for="website" class="col-form-label">website URL</label>
                                {{ Form::url('website',null,['class'=>'form-control','id'=>'heading_second']) }}
                                {{ Form::hidden('id',null) }}
                                @if($errors->has('website'))
                                    <div class="error" style="color: red;" >{{ $errors->first('website') }}</div>
                                @endif
                            </div>
                          
                        </div>

                          <div class="row">
                              <div class=" col-md-12">
                                  <label for="text" class="col-form-label">Text Here</label>
                                  {{ Form::textarea('address',null,['class'=>'form-control','id'=>'text','rows'=>'3', 'cols'=>'200']) }}
                                  @if($errors->has('address'))
                                      <div class="error" style="color: red;" >{{ $errors->first('address') }}</div>
                                  @endif
                              </div> 
                          </div>

                        <div class="row">
                          <div class="form-group col-md-6">
                             {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
                          </div>
                        </div>
                    </form>



                
              </div>
            </div>


          </div>
        </div>
      </div>
  </div>
</div>
@endsection

@push('scripts')
@endpush

resources/views/admin/contact/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Contact Lists</h4>
                <p class="card-category">List of Contacts</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
{{--                  <div class="gapMe" >--}}
{{--                    <a href="{{route('admin.contact.page.detail')}}" class="btn btn-primary float-right">Contact Page Detail</a>--}}
{{--                  </div>--}}
                  <table class="tableRouteManager">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>Name</th>
                      <th>Email Address</th>
                      <th>Subject</th>
                      <th>Message</th>
                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  $(document).ready(function() {
    $('.tableRouteManager').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.contact.list') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'subject', name: 'subject'},
            {data: 'message', name: 'message'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true,
            },
        ]
    });
  } );

  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableRouteManager').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      }).then(function(){
                          $(e).closest("tr").remove();
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }
</script>
@endpush